import Head from 'next/head'
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'
import Quote from '../components/Quote';

export default function Home() {
  const [quotes, setQuotes] = useState();
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      fetch('https://api.chucknorris.io/jokes/search?query=cats')
        .then(res => res.json())
        .then(quotes => {
          setQuotes(quotes.result)
          setIsLoading(false)
        })
    }
    fetchData()
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Quotes</h1>
        {isLoading ? <h2>Loading... </h2> :  quotes?.map(q => <Quote quote={q} key={q.id}/>)}
      </main>
    </div>
  )
}
